version: "3.8"

networks:
  internal:
    driver: bridge

services:

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: unless-stopped
    network_mode: host

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    privileged: true
    environment:
      - TZ=America/Chicago
    volumes:
      - ./homeassistant-data:/config
      - /run/dbus:/run/dbus:ro
      - ./homeassistant-config:/config/custom_configs:ro
    ports:
      - "8123:8123"
    restart: unless-stopped
    networks:
      - internal

  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    environment:
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.${DOMAIN}
    volumes:
      - ./mealie-data:/app/data/
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks:
      - internal

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      - AUDIOBOOKSHELF_UID=1000
      - AUDIOBOOKSHELF_GID=100
      - TZ=America/Chicago
    volumes:
      - ./audiobookshelf-data:/config
      - ./audiobookshelf-metadata:/metadata
      - ./audiobookshelf-media/audiobooks:/audiobooks
      - ./audiobookshelf-media/podcasts:/podcasts
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - internal
